version: '3.3'
services:
  db:
    image: mysql:5.7
    container_name: banco_mysql
    volumes:
      - ./:/home
      - ./data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'empresa'
      MYSQL_ROOT_PASSWORD: 'q1w2e3r4'
